language: ruby
cache: bundler
rvm:
  - 2.2.6
  - 2.3.3
before_script:
  - psql -c 'create database enju_purchase_request_dummy_test;' -U postgres
  - psql enju_purchase_request_dummy_test -c 'CREATE EXTENSION pgcrypto'
  - bundle exec rake db:migrate
after_script:
  - bundle exec codeclimate-test-reporter
services:
  - redis-server
env:
  - DB=postgresql
notifications:
  slack:
    secure: Y4M8QvIhqMoBDUu+m7vYX2m/8b8pJHsUqB0rufQCCg8zVstN6mcyG0ZZG9JFHkcQ6FV9fbLzMwUZmhqPsecaufB+1gaMl/KH+2MtqZ3O2e6pwDK8Ii22bYwHNtX2m8NSHRFPsT+wE7U46QpYAdL0x2PdyYjZeCLIvJReU1CmlsM=
dist: precise
sudo: false
addons:
  postgresql: "9.5"
